### ISSUE TITLE
Segfault generated by strlen in aur_{search,info}_parse

### ISSUE THREAD

**Issue by paraxic** [paraxic/ark#1]
Magically generated a segfault while trying to fill in aur_pkg_t structs, debug with gdb shows values are all okay based on what I see.

**Comment by kyrias** [comment]
`strlen`?  You sure you don't mean `strncpy`?

Because in `ark.c:19` you're statically allocating 500 `aur_pkg_t` structs on the stack, but `aur_pkg_t->name` &co are pointers, for which you never allocate any memory.  So you're trying to copy the data into memory through an uninitialized pointer.

**Comment by kyrias** [comment]
(Full backtrace with `-ggdb` would be useful, and the exact arguments you're testing with, so I know how to actually reproduce the exact bug you're talking about. :))

**Comment by paraxic** [comment]
you sir are amazing, allocating memory on the fly now to keep mem low, gonna have to figure out how to free it :P
